[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
new_project = "6PxW4uaB66n6WavKxacEPTrzPKEprX6MYbwZHQJXGQqp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
